// Code generated by mockery v2.53.4. DO NOT EDIT.

package identityaccess_mocks

import (
	context "context"

	domain "github.com/context-space/context-space/backend/internal/identityaccess/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockAPIKeyRepository is an autogenerated mock type for the APIKeyRepository type
type MockAPIKeyRepository struct {
	mock.Mock
}

type MockAPIKeyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIKeyRepository) EXPECT() *MockAPIKeyRepository_Expecter {
	return &MockAPIKeyRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, apiKey
func (_m *MockAPIKeyRepository) Create(ctx context.Context, apiKey *domain.APIKey) error {
	ret := _m.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.APIKey) error); ok {
		r0 = rf(ctx, apiKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAPIKeyRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockAPIKeyRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - apiKey *domain.APIKey
func (_e *MockAPIKeyRepository_Expecter) Create(ctx interface{}, apiKey interface{}) *MockAPIKeyRepository_Create_Call {
	return &MockAPIKeyRepository_Create_Call{Call: _e.mock.On("Create", ctx, apiKey)}
}

func (_c *MockAPIKeyRepository_Create_Call) Run(run func(ctx context.Context, apiKey *domain.APIKey)) *MockAPIKeyRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.APIKey))
	})
	return _c
}

func (_c *MockAPIKeyRepository_Create_Call) Return(_a0 error) *MockAPIKeyRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAPIKeyRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.APIKey) error) *MockAPIKeyRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockAPIKeyRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAPIKeyRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockAPIKeyRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAPIKeyRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockAPIKeyRepository_Delete_Call {
	return &MockAPIKeyRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockAPIKeyRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockAPIKeyRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAPIKeyRepository_Delete_Call) Return(_a0 error) *MockAPIKeyRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAPIKeyRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockAPIKeyRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function with given fields: ctx, id
func (_m *MockAPIKeyRepository) Get(ctx context.Context, id string) (*domain.APIKey, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.APIKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.APIKey, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.APIKey); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.APIKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPIKeyRepository_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockAPIKeyRepository_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAPIKeyRepository_Expecter) Get(ctx interface{}, id interface{}) *MockAPIKeyRepository_Get_Call {
	return &MockAPIKeyRepository_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *MockAPIKeyRepository_Get_Call) Run(run func(ctx context.Context, id string)) *MockAPIKeyRepository_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAPIKeyRepository_Get_Call) Return(_a0 *domain.APIKey, _a1 error) *MockAPIKeyRepository_Get_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPIKeyRepository_Get_Call) RunAndReturn(run func(context.Context, string) (*domain.APIKey, error)) *MockAPIKeyRepository_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetByKeyValue provides a mock function with given fields: ctx, value
func (_m *MockAPIKeyRepository) GetByKeyValue(ctx context.Context, value string) (*domain.APIKey, error) {
	ret := _m.Called(ctx, value)

	if len(ret) == 0 {
		panic("no return value specified for GetByKeyValue")
	}

	var r0 *domain.APIKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.APIKey, error)); ok {
		return rf(ctx, value)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.APIKey); ok {
		r0 = rf(ctx, value)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.APIKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, value)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPIKeyRepository_GetByKeyValue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByKeyValue'
type MockAPIKeyRepository_GetByKeyValue_Call struct {
	*mock.Call
}

// GetByKeyValue is a helper method to define mock.On call
//   - ctx context.Context
//   - value string
func (_e *MockAPIKeyRepository_Expecter) GetByKeyValue(ctx interface{}, value interface{}) *MockAPIKeyRepository_GetByKeyValue_Call {
	return &MockAPIKeyRepository_GetByKeyValue_Call{Call: _e.mock.On("GetByKeyValue", ctx, value)}
}

func (_c *MockAPIKeyRepository_GetByKeyValue_Call) Run(run func(ctx context.Context, value string)) *MockAPIKeyRepository_GetByKeyValue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAPIKeyRepository_GetByKeyValue_Call) Return(_a0 *domain.APIKey, _a1 error) *MockAPIKeyRepository_GetByKeyValue_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPIKeyRepository_GetByKeyValue_Call) RunAndReturn(run func(context.Context, string) (*domain.APIKey, error)) *MockAPIKeyRepository_GetByKeyValue_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUserID provides a mock function with given fields: ctx, userID
func (_m *MockAPIKeyRepository) ListByUserID(ctx context.Context, userID string) ([]*domain.APIKey, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListByUserID")
	}

	var r0 []*domain.APIKey
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*domain.APIKey, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*domain.APIKey); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.APIKey)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPIKeyRepository_ListByUserID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUserID'
type MockAPIKeyRepository_ListByUserID_Call struct {
	*mock.Call
}

// ListByUserID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID string
func (_e *MockAPIKeyRepository_Expecter) ListByUserID(ctx interface{}, userID interface{}) *MockAPIKeyRepository_ListByUserID_Call {
	return &MockAPIKeyRepository_ListByUserID_Call{Call: _e.mock.On("ListByUserID", ctx, userID)}
}

func (_c *MockAPIKeyRepository_ListByUserID_Call) Run(run func(ctx context.Context, userID string)) *MockAPIKeyRepository_ListByUserID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockAPIKeyRepository_ListByUserID_Call) Return(_a0 []*domain.APIKey, _a1 error) *MockAPIKeyRepository_ListByUserID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPIKeyRepository_ListByUserID_Call) RunAndReturn(run func(context.Context, string) ([]*domain.APIKey, error)) *MockAPIKeyRepository_ListByUserID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, apiKey
func (_m *MockAPIKeyRepository) Update(ctx context.Context, apiKey *domain.APIKey) error {
	ret := _m.Called(ctx, apiKey)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.APIKey) error); ok {
		r0 = rf(ctx, apiKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockAPIKeyRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockAPIKeyRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - apiKey *domain.APIKey
func (_e *MockAPIKeyRepository_Expecter) Update(ctx interface{}, apiKey interface{}) *MockAPIKeyRepository_Update_Call {
	return &MockAPIKeyRepository_Update_Call{Call: _e.mock.On("Update", ctx, apiKey)}
}

func (_c *MockAPIKeyRepository_Update_Call) Run(run func(ctx context.Context, apiKey *domain.APIKey)) *MockAPIKeyRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.APIKey))
	})
	return _c
}

func (_c *MockAPIKeyRepository_Update_Call) Return(_a0 error) *MockAPIKeyRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAPIKeyRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.APIKey) error) *MockAPIKeyRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAPIKeyRepository creates a new instance of MockAPIKeyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIKeyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIKeyRepository {
	mock := &MockAPIKeyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
