// Code generated by mockery v2.53.4. DO NOT EDIT.

package providercore_mocks

import (
	context "context"

	domain "github.com/context-space/context-space/backend/internal/providercore/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockProviderRepository is an autogenerated mock type for the ProviderRepository type
type MockProviderRepository struct {
	mock.Mock
}

type MockProviderRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProviderRepository) EXPECT() *MockProviderRepository_Expecter {
	return &MockProviderRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, provider
func (_m *MockProviderRepository) Create(ctx context.Context, provider *domain.Provider) error {
	ret := _m.Called(ctx, provider)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Provider) error); ok {
		r0 = rf(ctx, provider)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProviderRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockProviderRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - provider *domain.Provider
func (_e *MockProviderRepository_Expecter) Create(ctx interface{}, provider interface{}) *MockProviderRepository_Create_Call {
	return &MockProviderRepository_Create_Call{Call: _e.mock.On("Create", ctx, provider)}
}

func (_c *MockProviderRepository_Create_Call) Run(run func(ctx context.Context, provider *domain.Provider)) *MockProviderRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Provider))
	})
	return _c
}

func (_c *MockProviderRepository_Create_Call) Return(_a0 error) *MockProviderRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProviderRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.Provider) error) *MockProviderRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *MockProviderRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProviderRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockProviderRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockProviderRepository_Expecter) Delete(ctx interface{}, id interface{}) *MockProviderRepository_Delete_Call {
	return &MockProviderRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockProviderRepository_Delete_Call) Run(run func(ctx context.Context, id string)) *MockProviderRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProviderRepository_Delete_Call) Return(_a0 error) *MockProviderRepository_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProviderRepository_Delete_Call) RunAndReturn(run func(context.Context, string) error) *MockProviderRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MockProviderRepository) GetByID(ctx context.Context, id string) (*domain.Provider, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *domain.Provider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Provider, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Provider); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Provider)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProviderRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockProviderRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockProviderRepository_Expecter) GetByID(ctx interface{}, id interface{}) *MockProviderRepository_GetByID_Call {
	return &MockProviderRepository_GetByID_Call{Call: _e.mock.On("GetByID", ctx, id)}
}

func (_c *MockProviderRepository_GetByID_Call) Run(run func(ctx context.Context, id string)) *MockProviderRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProviderRepository_GetByID_Call) Return(_a0 *domain.Provider, _a1 error) *MockProviderRepository_GetByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProviderRepository_GetByID_Call) RunAndReturn(run func(context.Context, string) (*domain.Provider, error)) *MockProviderRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByIdentifier provides a mock function with given fields: ctx, identifier
func (_m *MockProviderRepository) GetByIdentifier(ctx context.Context, identifier string) (*domain.Provider, error) {
	ret := _m.Called(ctx, identifier)

	if len(ret) == 0 {
		panic("no return value specified for GetByIdentifier")
	}

	var r0 *domain.Provider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.Provider, error)); ok {
		return rf(ctx, identifier)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.Provider); ok {
		r0 = rf(ctx, identifier)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Provider)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, identifier)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProviderRepository_GetByIdentifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByIdentifier'
type MockProviderRepository_GetByIdentifier_Call struct {
	*mock.Call
}

// GetByIdentifier is a helper method to define mock.On call
//   - ctx context.Context
//   - identifier string
func (_e *MockProviderRepository_Expecter) GetByIdentifier(ctx interface{}, identifier interface{}) *MockProviderRepository_GetByIdentifier_Call {
	return &MockProviderRepository_GetByIdentifier_Call{Call: _e.mock.On("GetByIdentifier", ctx, identifier)}
}

func (_c *MockProviderRepository_GetByIdentifier_Call) Run(run func(ctx context.Context, identifier string)) *MockProviderRepository_GetByIdentifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockProviderRepository_GetByIdentifier_Call) Return(_a0 *domain.Provider, _a1 error) *MockProviderRepository_GetByIdentifier_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProviderRepository_GetByIdentifier_Call) RunAndReturn(run func(context.Context, string) (*domain.Provider, error)) *MockProviderRepository_GetByIdentifier_Call {
	_c.Call.Return(run)
	return _c
}

// ListBasicProviders provides a mock function with given fields: ctx
func (_m *MockProviderRepository) ListBasicProviders(ctx context.Context) ([]*domain.Provider, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListBasicProviders")
	}

	var r0 []*domain.Provider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Provider, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Provider); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Provider)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProviderRepository_ListBasicProviders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBasicProviders'
type MockProviderRepository_ListBasicProviders_Call struct {
	*mock.Call
}

// ListBasicProviders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProviderRepository_Expecter) ListBasicProviders(ctx interface{}) *MockProviderRepository_ListBasicProviders_Call {
	return &MockProviderRepository_ListBasicProviders_Call{Call: _e.mock.On("ListBasicProviders", ctx)}
}

func (_c *MockProviderRepository_ListBasicProviders_Call) Run(run func(ctx context.Context)) *MockProviderRepository_ListBasicProviders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockProviderRepository_ListBasicProviders_Call) Return(_a0 []*domain.Provider, _a1 error) *MockProviderRepository_ListBasicProviders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProviderRepository_ListBasicProviders_Call) RunAndReturn(run func(context.Context) ([]*domain.Provider, error)) *MockProviderRepository_ListBasicProviders_Call {
	_c.Call.Return(run)
	return _c
}

// ListByIDs provides a mock function with given fields: ctx, ids
func (_m *MockProviderRepository) ListByIDs(ctx context.Context, ids []string) ([]*domain.Provider, error) {
	ret := _m.Called(ctx, ids)

	if len(ret) == 0 {
		panic("no return value specified for ListByIDs")
	}

	var r0 []*domain.Provider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) ([]*domain.Provider, error)); ok {
		return rf(ctx, ids)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) []*domain.Provider); ok {
		r0 = rf(ctx, ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Provider)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, ids)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProviderRepository_ListByIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByIDs'
type MockProviderRepository_ListByIDs_Call struct {
	*mock.Call
}

// ListByIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - ids []string
func (_e *MockProviderRepository_Expecter) ListByIDs(ctx interface{}, ids interface{}) *MockProviderRepository_ListByIDs_Call {
	return &MockProviderRepository_ListByIDs_Call{Call: _e.mock.On("ListByIDs", ctx, ids)}
}

func (_c *MockProviderRepository_ListByIDs_Call) Run(run func(ctx context.Context, ids []string)) *MockProviderRepository_ListByIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockProviderRepository_ListByIDs_Call) Return(_a0 []*domain.Provider, _a1 error) *MockProviderRepository_ListByIDs_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProviderRepository_ListByIDs_Call) RunAndReturn(run func(context.Context, []string) ([]*domain.Provider, error)) *MockProviderRepository_ListByIDs_Call {
	_c.Call.Return(run)
	return _c
}

// ListFullProviders provides a mock function with given fields: ctx
func (_m *MockProviderRepository) ListFullProviders(ctx context.Context) ([]*domain.Provider, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListFullProviders")
	}

	var r0 []*domain.Provider
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]*domain.Provider, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []*domain.Provider); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.Provider)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockProviderRepository_ListFullProviders_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFullProviders'
type MockProviderRepository_ListFullProviders_Call struct {
	*mock.Call
}

// ListFullProviders is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockProviderRepository_Expecter) ListFullProviders(ctx interface{}) *MockProviderRepository_ListFullProviders_Call {
	return &MockProviderRepository_ListFullProviders_Call{Call: _e.mock.On("ListFullProviders", ctx)}
}

func (_c *MockProviderRepository_ListFullProviders_Call) Run(run func(ctx context.Context)) *MockProviderRepository_ListFullProviders_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockProviderRepository_ListFullProviders_Call) Return(_a0 []*domain.Provider, _a1 error) *MockProviderRepository_ListFullProviders_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProviderRepository_ListFullProviders_Call) RunAndReturn(run func(context.Context) ([]*domain.Provider, error)) *MockProviderRepository_ListFullProviders_Call {
	_c.Call.Return(run)
	return _c
}

// SyncTagsToProvider provides a mock function with given fields: ctx, providerIdentifier, tags
func (_m *MockProviderRepository) SyncTagsToProvider(ctx context.Context, providerIdentifier string, tags []string) error {
	ret := _m.Called(ctx, providerIdentifier, tags)

	if len(ret) == 0 {
		panic("no return value specified for SyncTagsToProvider")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []string) error); ok {
		r0 = rf(ctx, providerIdentifier, tags)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProviderRepository_SyncTagsToProvider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncTagsToProvider'
type MockProviderRepository_SyncTagsToProvider_Call struct {
	*mock.Call
}

// SyncTagsToProvider is a helper method to define mock.On call
//   - ctx context.Context
//   - providerIdentifier string
//   - tags []string
func (_e *MockProviderRepository_Expecter) SyncTagsToProvider(ctx interface{}, providerIdentifier interface{}, tags interface{}) *MockProviderRepository_SyncTagsToProvider_Call {
	return &MockProviderRepository_SyncTagsToProvider_Call{Call: _e.mock.On("SyncTagsToProvider", ctx, providerIdentifier, tags)}
}

func (_c *MockProviderRepository_SyncTagsToProvider_Call) Run(run func(ctx context.Context, providerIdentifier string, tags []string)) *MockProviderRepository_SyncTagsToProvider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]string))
	})
	return _c
}

func (_c *MockProviderRepository_SyncTagsToProvider_Call) Return(_a0 error) *MockProviderRepository_SyncTagsToProvider_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProviderRepository_SyncTagsToProvider_Call) RunAndReturn(run func(context.Context, string, []string) error) *MockProviderRepository_SyncTagsToProvider_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, provider
func (_m *MockProviderRepository) Update(ctx context.Context, provider *domain.Provider) error {
	ret := _m.Called(ctx, provider)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Provider) error); ok {
		r0 = rf(ctx, provider)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockProviderRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockProviderRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - provider *domain.Provider
func (_e *MockProviderRepository_Expecter) Update(ctx interface{}, provider interface{}) *MockProviderRepository_Update_Call {
	return &MockProviderRepository_Update_Call{Call: _e.mock.On("Update", ctx, provider)}
}

func (_c *MockProviderRepository_Update_Call) Run(run func(ctx context.Context, provider *domain.Provider)) *MockProviderRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.Provider))
	})
	return _c
}

func (_c *MockProviderRepository_Update_Call) Return(_a0 error) *MockProviderRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockProviderRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.Provider) error) *MockProviderRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProviderRepository creates a new instance of MockProviderRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProviderRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProviderRepository {
	mock := &MockProviderRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
