// Code generated by mockery v2.53.4. DO NOT EDIT.

package provideradapter_mocks

import (
	context "context"

	domain "github.com/context-space/context-space/backend/internal/provideradapter/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockAPIKeyAdapter is an autogenerated mock type for the APIKeyAdapter type
type MockAPIKeyAdapter struct {
	mock.Mock
}

type MockAPIKeyAdapter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAPIKeyAdapter) EXPECT() *MockAPIKeyAdapter_Expecter {
	return &MockAPIKeyAdapter_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: ctx, operationID, params, credential
func (_m *MockAPIKeyAdapter) Execute(ctx context.Context, operationID string, params map[string]interface{}, credential interface{}) (interface{}, error) {
	ret := _m.Called(ctx, operationID, params, credential)

	if len(ret) == 0 {
		panic("no return value specified for Execute")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}, interface{}) (interface{}, error)); ok {
		return rf(ctx, operationID, params, credential)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, map[string]interface{}, interface{}) interface{}); ok {
		r0 = rf(ctx, operationID, params, credential)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, map[string]interface{}, interface{}) error); ok {
		r1 = rf(ctx, operationID, params, credential)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAPIKeyAdapter_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MockAPIKeyAdapter_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - ctx context.Context
//   - operationID string
//   - params map[string]interface{}
//   - credential interface{}
func (_e *MockAPIKeyAdapter_Expecter) Execute(ctx interface{}, operationID interface{}, params interface{}, credential interface{}) *MockAPIKeyAdapter_Execute_Call {
	return &MockAPIKeyAdapter_Execute_Call{Call: _e.mock.On("Execute", ctx, operationID, params, credential)}
}

func (_c *MockAPIKeyAdapter_Execute_Call) Run(run func(ctx context.Context, operationID string, params map[string]interface{}, credential interface{})) *MockAPIKeyAdapter_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(map[string]interface{}), args[3].(interface{}))
	})
	return _c
}

func (_c *MockAPIKeyAdapter_Execute_Call) Return(_a0 interface{}, _a1 error) *MockAPIKeyAdapter_Execute_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAPIKeyAdapter_Execute_Call) RunAndReturn(run func(context.Context, string, map[string]interface{}, interface{}) (interface{}, error)) *MockAPIKeyAdapter_Execute_Call {
	_c.Call.Return(run)
	return _c
}

// GetProviderAdapterInfo provides a mock function with no fields
func (_m *MockAPIKeyAdapter) GetProviderAdapterInfo() *domain.ProviderAdapterInfo {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProviderAdapterInfo")
	}

	var r0 *domain.ProviderAdapterInfo
	if rf, ok := ret.Get(0).(func() *domain.ProviderAdapterInfo); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.ProviderAdapterInfo)
		}
	}

	return r0
}

// MockAPIKeyAdapter_GetProviderAdapterInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProviderAdapterInfo'
type MockAPIKeyAdapter_GetProviderAdapterInfo_Call struct {
	*mock.Call
}

// GetProviderAdapterInfo is a helper method to define mock.On call
func (_e *MockAPIKeyAdapter_Expecter) GetProviderAdapterInfo() *MockAPIKeyAdapter_GetProviderAdapterInfo_Call {
	return &MockAPIKeyAdapter_GetProviderAdapterInfo_Call{Call: _e.mock.On("GetProviderAdapterInfo")}
}

func (_c *MockAPIKeyAdapter_GetProviderAdapterInfo_Call) Run(run func()) *MockAPIKeyAdapter_GetProviderAdapterInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAPIKeyAdapter_GetProviderAdapterInfo_Call) Return(_a0 *domain.ProviderAdapterInfo) *MockAPIKeyAdapter_GetProviderAdapterInfo_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockAPIKeyAdapter_GetProviderAdapterInfo_Call) RunAndReturn(run func() *domain.ProviderAdapterInfo) *MockAPIKeyAdapter_GetProviderAdapterInfo_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAPIKeyAdapter creates a new instance of MockAPIKeyAdapter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAPIKeyAdapter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAPIKeyAdapter {
	mock := &MockAPIKeyAdapter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
