// Code generated by mockery v2.53.4. DO NOT EDIT.

package credentialmanagement_mocks

import (
	context "context"

	domain "github.com/context-space/context-space/backend/internal/credentialmanagement/domain"
	mock "github.com/stretchr/testify/mock"

	time "time"
)

// MockOAuthCredentialRepository is an autogenerated mock type for the OAuthCredentialRepository type
type MockOAuthCredentialRepository struct {
	mock.Mock
}

type MockOAuthCredentialRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOAuthCredentialRepository) EXPECT() *MockOAuthCredentialRepository_Expecter {
	return &MockOAuthCredentialRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, credential
func (_m *MockOAuthCredentialRepository) Create(ctx context.Context, credential *domain.OAuthCredential) error {
	ret := _m.Called(ctx, credential)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.OAuthCredential) error); ok {
		r0 = rf(ctx, credential)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOAuthCredentialRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockOAuthCredentialRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - credential *domain.OAuthCredential
func (_e *MockOAuthCredentialRepository_Expecter) Create(ctx interface{}, credential interface{}) *MockOAuthCredentialRepository_Create_Call {
	return &MockOAuthCredentialRepository_Create_Call{Call: _e.mock.On("Create", ctx, credential)}
}

func (_c *MockOAuthCredentialRepository_Create_Call) Run(run func(ctx context.Context, credential *domain.OAuthCredential)) *MockOAuthCredentialRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.OAuthCredential))
	})
	return _c
}

func (_c *MockOAuthCredentialRepository_Create_Call) Return(_a0 error) *MockOAuthCredentialRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOAuthCredentialRepository_Create_Call) RunAndReturn(run func(context.Context, *domain.OAuthCredential) error) *MockOAuthCredentialRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCredentialID provides a mock function with given fields: ctx, credentialID
func (_m *MockOAuthCredentialRepository) GetByCredentialID(ctx context.Context, credentialID string) (*domain.OAuthCredential, error) {
	ret := _m.Called(ctx, credentialID)

	if len(ret) == 0 {
		panic("no return value specified for GetByCredentialID")
	}

	var r0 *domain.OAuthCredential
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*domain.OAuthCredential, error)); ok {
		return rf(ctx, credentialID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *domain.OAuthCredential); ok {
		r0 = rf(ctx, credentialID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.OAuthCredential)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, credentialID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOAuthCredentialRepository_GetByCredentialID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCredentialID'
type MockOAuthCredentialRepository_GetByCredentialID_Call struct {
	*mock.Call
}

// GetByCredentialID is a helper method to define mock.On call
//   - ctx context.Context
//   - credentialID string
func (_e *MockOAuthCredentialRepository_Expecter) GetByCredentialID(ctx interface{}, credentialID interface{}) *MockOAuthCredentialRepository_GetByCredentialID_Call {
	return &MockOAuthCredentialRepository_GetByCredentialID_Call{Call: _e.mock.On("GetByCredentialID", ctx, credentialID)}
}

func (_c *MockOAuthCredentialRepository_GetByCredentialID_Call) Run(run func(ctx context.Context, credentialID string)) *MockOAuthCredentialRepository_GetByCredentialID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockOAuthCredentialRepository_GetByCredentialID_Call) Return(_a0 *domain.OAuthCredential, _a1 error) *MockOAuthCredentialRepository_GetByCredentialID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOAuthCredentialRepository_GetByCredentialID_Call) RunAndReturn(run func(context.Context, string) (*domain.OAuthCredential, error)) *MockOAuthCredentialRepository_GetByCredentialID_Call {
	_c.Call.Return(run)
	return _c
}

// ListByExpiryWithin provides a mock function with given fields: ctx, expiry
func (_m *MockOAuthCredentialRepository) ListByExpiryWithin(ctx context.Context, expiry time.Time) ([]*domain.OAuthCredential, error) {
	ret := _m.Called(ctx, expiry)

	if len(ret) == 0 {
		panic("no return value specified for ListByExpiryWithin")
	}

	var r0 []*domain.OAuthCredential
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) ([]*domain.OAuthCredential, error)); ok {
		return rf(ctx, expiry)
	}
	if rf, ok := ret.Get(0).(func(context.Context, time.Time) []*domain.OAuthCredential); ok {
		r0 = rf(ctx, expiry)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*domain.OAuthCredential)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = rf(ctx, expiry)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockOAuthCredentialRepository_ListByExpiryWithin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByExpiryWithin'
type MockOAuthCredentialRepository_ListByExpiryWithin_Call struct {
	*mock.Call
}

// ListByExpiryWithin is a helper method to define mock.On call
//   - ctx context.Context
//   - expiry time.Time
func (_e *MockOAuthCredentialRepository_Expecter) ListByExpiryWithin(ctx interface{}, expiry interface{}) *MockOAuthCredentialRepository_ListByExpiryWithin_Call {
	return &MockOAuthCredentialRepository_ListByExpiryWithin_Call{Call: _e.mock.On("ListByExpiryWithin", ctx, expiry)}
}

func (_c *MockOAuthCredentialRepository_ListByExpiryWithin_Call) Run(run func(ctx context.Context, expiry time.Time)) *MockOAuthCredentialRepository_ListByExpiryWithin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(time.Time))
	})
	return _c
}

func (_c *MockOAuthCredentialRepository_ListByExpiryWithin_Call) Return(_a0 []*domain.OAuthCredential, _a1 error) *MockOAuthCredentialRepository_ListByExpiryWithin_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockOAuthCredentialRepository_ListByExpiryWithin_Call) RunAndReturn(run func(context.Context, time.Time) ([]*domain.OAuthCredential, error)) *MockOAuthCredentialRepository_ListByExpiryWithin_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, credential
func (_m *MockOAuthCredentialRepository) Update(ctx context.Context, credential *domain.OAuthCredential) error {
	ret := _m.Called(ctx, credential)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.OAuthCredential) error); ok {
		r0 = rf(ctx, credential)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockOAuthCredentialRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockOAuthCredentialRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - credential *domain.OAuthCredential
func (_e *MockOAuthCredentialRepository_Expecter) Update(ctx interface{}, credential interface{}) *MockOAuthCredentialRepository_Update_Call {
	return &MockOAuthCredentialRepository_Update_Call{Call: _e.mock.On("Update", ctx, credential)}
}

func (_c *MockOAuthCredentialRepository_Update_Call) Run(run func(ctx context.Context, credential *domain.OAuthCredential)) *MockOAuthCredentialRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*domain.OAuthCredential))
	})
	return _c
}

func (_c *MockOAuthCredentialRepository_Update_Call) Return(_a0 error) *MockOAuthCredentialRepository_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockOAuthCredentialRepository_Update_Call) RunAndReturn(run func(context.Context, *domain.OAuthCredential) error) *MockOAuthCredentialRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockOAuthCredentialRepository creates a new instance of MockOAuthCredentialRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOAuthCredentialRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOAuthCredentialRepository {
	mock := &MockOAuthCredentialRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
