// Code generated by mockery v2.53.4. DO NOT EDIT.

package integration_mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockTokenRefreshProvider is an autogenerated mock type for the TokenRefreshProvider type
type MockTokenRefreshProvider struct {
	mock.Mock
}

type MockTokenRefreshProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRefreshProvider) EXPECT() *MockTokenRefreshProvider_Expecter {
	return &MockTokenRefreshProvider_Expecter{mock: &_m.Mock}
}

// RefreshAccessToken provides a mock function with given fields: ctx, providerIdentifier, credential
func (_m *MockTokenRefreshProvider) RefreshAccessToken(ctx context.Context, providerIdentifier string, credential interface{}) (interface{}, error) {
	ret := _m.Called(ctx, providerIdentifier, credential)

	if len(ret) == 0 {
		panic("no return value specified for RefreshAccessToken")
	}

	var r0 interface{}
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) (interface{}, error)); ok {
		return rf(ctx, providerIdentifier, credential)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, interface{}) interface{}); ok {
		r0 = rf(ctx, providerIdentifier, credential)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, interface{}) error); ok {
		r1 = rf(ctx, providerIdentifier, credential)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenRefreshProvider_RefreshAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RefreshAccessToken'
type MockTokenRefreshProvider_RefreshAccessToken_Call struct {
	*mock.Call
}

// RefreshAccessToken is a helper method to define mock.On call
//   - ctx context.Context
//   - providerIdentifier string
//   - credential interface{}
func (_e *MockTokenRefreshProvider_Expecter) RefreshAccessToken(ctx interface{}, providerIdentifier interface{}, credential interface{}) *MockTokenRefreshProvider_RefreshAccessToken_Call {
	return &MockTokenRefreshProvider_RefreshAccessToken_Call{Call: _e.mock.On("RefreshAccessToken", ctx, providerIdentifier, credential)}
}

func (_c *MockTokenRefreshProvider_RefreshAccessToken_Call) Run(run func(ctx context.Context, providerIdentifier string, credential interface{})) *MockTokenRefreshProvider_RefreshAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(interface{}))
	})
	return _c
}

func (_c *MockTokenRefreshProvider_RefreshAccessToken_Call) Return(_a0 interface{}, _a1 error) *MockTokenRefreshProvider_RefreshAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenRefreshProvider_RefreshAccessToken_Call) RunAndReturn(run func(context.Context, string, interface{}) (interface{}, error)) *MockTokenRefreshProvider_RefreshAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenRefreshProvider creates a new instance of MockTokenRefreshProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRefreshProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRefreshProvider {
	mock := &MockTokenRefreshProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
