name: "CLA Assistant"
on:
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, closed, synchronize]

permissions:
  actions: write
  contents: write
  pull-requests: write
  statuses: write
  repository-projects: read

jobs:
  CLAAssistant:
    runs-on: ubuntu-latest
    steps:
      - name: "CLA Assistant"
        if: (github.event.comment.body == 'recheck' || github.event.comment.body == 'I have read the CLA Document and I hereby sign the CLA') || github.event_name == 'pull_request_target'
        uses: contributor-assistant/github-action@v2.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          path-to-signatures: "signatures/version1/cla.json"
          path-to-document: "https://github.com/context-space/context-space/blob/main/CLA.md"
          branch: "main"
          allowlist: dependabot[bot],github-actions[bot]
          create-file-commit-message: "chore(cla): create file for storing CLA signatures"
          signed-commit-message: "chore(cla): CLA signed by contributor ($contributorName)"
          custom-notsigned-prcomment: |
            👋 **Thank you for your contribution to Context Space!**

            Before we can merge this pull request, please sign our Contributor License Agreement (CLA).

            📋 **Please read our CLA document:** https://github.com/context-space/context-space/blob/main/CLA.md

            ✍️ **To sign the CLA, simply comment on this PR:**
            ```
            I have read the CLA Document and I hereby sign the CLA
            ```

            Once you've signed, we'll automatically update the PR status. Thank you! 🚀

            If you have any questions, feel free to reach out to the maintainers.
          custom-allsigned-prcomment: |
            ✅ **Awesome!** All contributors have signed the CLA.

            Thank you for your contribution to Context Space! 🎉
          lock-pullrequest-aftermerge: true
          suggest-recheck: true
